# Generated by Django 5.1.7 on 2025-03-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='No description', max_length=500),
            preserve_default=False,
        ),
    ]
